Added Inchoo_MyFirst Module
ddancho/magento_2.4.2 pull request #1
Opened 2021-03-23 10:23 UTC by ddancho

2021-03-23 11:36 UTC, tnikcevs commented on app/code/Inchoo/MyFirst/composer.json
> +{}
primjer composer.json-a koji češ raditi i u idućim modulima

pod require idu moduli koje si koristio u svojim php fileovima sa "use", u ovom slučaju može samo framework

primjer: 
{
  "name": "inchoo/module-my-first",
  "description": "First M2 module",
  "type": "magento2-module",
  "version": "1.0.0",
  "require": {
    "php": "~7.1.3||~7.2.0||~7.3.0",
    "magento/framework": "*"
  },
  "autoload": {
    "files": [ "registration.php" ],
    "psr-4": {
      "Inchoo\\MyFirst\\": ""
    }
  },
  "authors": [
    {
      "name": "Inchoo",
      "email": "backend@inchoo.net",
      "homepage": "https://inchoo.net/",
      "role": "Developer"
    }
  ]
}

2021-03-23 11:37 UTC, tnikcevs requested changes
composer.json

2021-04-06 07:01 UTC, tnikcevs approved these changes

2021-04-06 07:22 UTC, ddancho commented
merging inchoo_myfirst module into main

2021-04-06 07:22 UTC, merged