Task 03
ddancho/magento_2.4.2 pull request #2
Opened 2021-03-25 13:09 UTC by ddancho

2021-03-25 14:11 UTC, ivanmatozan requested changes

2021-03-25 14:11 UTC, ivanmatozan commented on app/design/frontend/Inchoo/custom/Magento_Theme/templates/hello-world.phtml
> +<?php
ako odeš na `sample03/result/page`, hoće li se koristiti ovaj template?

2021-03-25 14:11 UTC, ivanmatozan commented on app/code/Inchoo/Sample03/view/frontend/templates/homepage2.phtml
> +<p>Hello World</p>
stavi `Hello World` string u translate funkciju i escape ju.

2021-03-31 13:41 UTC, ivanmatozan approved these changes

2021-03-31 13:41 UTC, ivanmatozan commented on app/code/Inchoo/Sample03/view/frontend/templates/homepage2.phtml
> +<p><?= $escaper->escapeHtml(__('Hello World')) ?> </p>
code check će baciti error jer nije escaped string

2021-04-06 07:30 UTC, ddancho commented
merging task03 into main

2021-04-06 07:30 UTC, merged