Object manager
ddancho/magento_2.4.2 pull request #3
Opened 2021-03-25 14:03 UTC by ddancho

2021-03-25 19:28 UTC, ivanmatozan commented on app/code/Inchoo/Sample02/etc/di.xml
> +    <preference for="Inchoo\Sample02\Model\Preference\DummyOne" type="Inchoo\Sample02\Model\Preference\DummyTwo" />
što se dogodi kada napraviš request na `sample02/di/override` URL path?

2021-03-25 19:32 UTC, ivanmatozan commented on app/code/Inchoo/Sample02/etc/di.xml
> +    <type name="Inchoo\Sample02\Controller\ObjectManager\LazyLoad">
gdje ti je `Inchoo\Sample02\Controller\ObjectManager\LazyLoad` klasa?

2021-03-25 19:33 UTC, ivanmatozan requested changes
.

2021-03-26 09:00 UTC, ddancho commented on app/code/Inchoo/Sample02/etc/di.xml
> +    <preference for="Inchoo\Sample02\Model\Preference\DummyOne" type="Inchoo\Sample02\Model\Preference\DummyTwo" />
exception naravno...

2021-03-31 13:38 UTC, ivanmatozan commented on app/code/Inchoo/Sample02/etc/di.xml
> +    <preference for="Inchoo\Sample02\Model\Preference\DummyOne" type="Inchoo\Sample02\Model\Preference\DummyTwo" />
znaš li zašto?

2021-03-31 13:38 UTC, ivanmatozan approved these changes

2021-04-06 07:29 UTC, ddancho commented
merging object_manager into main

2021-04-06 07:29 UTC, merged