Request flow processing
ddancho/magento_2.4.2 pull request #4
Opened 2021-03-25 14:04 UTC by ddancho

2021-03-25 19:07 UTC, ivanmatozan commented on app/code/Inchoo/Sample01/etc/frontend/routes.xml
> +        <route id="sample01" frontName="sample01">
`frontName` je trebalo promjeniti u `hello`

2021-03-25 19:09 UTC, ivanmatozan requested changes
- nije riješen zadatak s `redirect` i `result` result types.

2021-03-26 08:33 UTC, ddancho commented
zašto misliš da nije rješen , kreirao sam dva nova kontrolera s redirect i forward tipovima ( btw jel to typo result result ? )

2021-03-31 13:33 UTC, ivanmatozan commented
> * nije riješen zadatak s `redirect` i `result` result types.

2021-03-31 13:33 UTC, ivanmatozan commented
> zašto misliš da nije rješen , kreirao sam dva nova kontrolera s redirect i forward tipovima ( btw jel to typo result result ? )

nešto sam zabrijo, ok je

2021-03-31 13:34 UTC, ivanmatozan approved these changes

2021-04-06 07:28 UTC, ddancho commented
merging request_flow_processing into main

2021-04-06 07:28 UTC, merged