service contracts changes
ddancho/magento_2.4.2 pull request #6
Opened 2021-04-06 07:19 UTC by ddancho

2021-04-06 07:29 UTC, ivanmatozan requested changes

2021-04-06 07:29 UTC, ivanmatozan commented on app/code/Inchoo/Sample05/ViewModel/Event.php
> +
Nisi morao injectati Filter i FilterGroup objeckte, imaš metodu na SearchCriteriaBuilderu

```suggestion
        $this->searchCriteriaBuilder->addFilter('status', 1);
```

2021-04-06 07:29 UTC, ivanmatozan commented on app/etc/config.php
> +        'Inchoo_Sample04' => 0,
što `Inchoo_Sample04` radi ovdje? Ako ti je disabled i ti napraviš `setup:upgrade` to će ti obrisati sve sample04 tablice

2021-04-06 07:29 UTC, ivanmatozan commented on app/code/Inchoo/Sample05/ViewModel/Event.php
> +    public function getEventList(int $pageSize = 5): array
ja ne bi ovdje ograničio na 5. Metoda se poziva u template-u, napravi to tamo. Ovako si ograničio za sve korisnike ove metode

2021-04-07 01:01 UTC, ivanmatozan commented on app/code/Inchoo/Sample05/etc/webapi.xml
> +            <resource ref="anonymous"/><!-- anyone can access this endpoint -->
ne bi dopustio da bilo tko može koristiti delete API endpoint

2021-04-13 10:57 UTC, ivanmatozan approved these changes

2021-04-14 07:22 UTC, ddancho commented
merging service contracts with main

2021-04-14 07:22 UTC, merged