adminhtml task
ddancho/magento_2.4.2 pull request #8
Opened 2021-04-08 10:45 UTC by ddancho

2021-04-08 12:10 UTC, ivanmatozan requested changes

2021-04-08 12:10 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/view/adminhtml/templates/hello-world.phtml
> +    <p><?= $block->escapeHtml($viewModel->getContent()) ?></p>
ovo ti se neće prikazati ako nema `$title`

2021-04-13 10:55 UTC, ivanmatozan approved these changes

2021-04-13 10:55 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +        $resultRedirect = $this->resultFactory->create($this->resultFactory::TYPE_REDIRECT);
zašto ova izmjena?

2021-04-14 07:25 UTC, ddancho commented
merging adminhtml with main

2021-04-14 07:25 UTC, merged